--- #YAML:1.0
name:                Gnome2
version:             1.041
abstract:            Perl interface to the 2.x series of the GNOME libraries
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    ExtUtils::Depends:             0.20
    ExtUtils::PkgConfig:           1.03
    Glib:                          1.04
    Gnome2::Canvas:                1.00
    Gnome2::VFS:                   1.00
    Gtk2:                          1.00
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
