---
abstract: 'Perl interface to the 2.x series of the GNOME libraries'
author:
  - 'Gnome2 Perl Team <gtk-perl-list at gnome dot org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::Depends: 0.20
  ExtUtils::PkgConfig: 1.03
  Glib: 1.04
  Gnome2::Canvas: 1.00
  Gnome2::VFS: 1.00
  Gtk2: 1.00
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132830'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gnome2
no_index:
  directory:
    - t
    - inc
  file:
    - inc/MakeHelper.pm
requires:
  ExtUtils::Depends: 0.20
  ExtUtils::PkgConfig: 1.03
  Glib: 1.04
  Gnome2::Canvas: 1.00
  Gnome2::VFS: 1.00
  Gtk2: 1.00
resources:
  MailingList: https://mail.gnome.org/mailman/listinfo/gtk-perl-list
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Gnome2
  homepage: http://gtk2-perl.sourceforge.net
  license: http://www.gnu.org/licenses/lgpl-2.1.html
  repository: git://git.gnome.org/perl-Gnome2
version: 1.045
