#!/usr/bin/perl -w
use strict;
use Gnome2;

# $Header: /cvsroot/gtk2-perl/gtk2-perl-xs/Gnome2/t/GnomeURL,v 1.1 2003/09/26 14:33:17 kaffeetisch Exp $

###############################################################################

SKIP: {
  skip("You don't appear to have the GNOME session manager running.", 0)
    unless (-d "$ENV{ HOME }/.gconfd" &&
            -d "$ENV{ HOME }/.gnome2");

  my $application = Gnome2::Program -> init("zenity", "0.1", "libgnomeui", app_datadir => "/usr/share");

  skip("Couldn't connect to the session manager.", 0)
    unless (Gnome2::Client -> new() -> connected());

  #############################################################################

  Gnome2::URL -> show("http://ftp.freenet.de");
}
