#!/usr/bin/perl -w
use strict;
use Gnome2;

# $Header: /cvsroot/gtk2-perl/gtk2-perl-xs/Gnome2/t/GnomeURL,v 1.3 2003/12/15 00:17:24 kaffeetisch Exp $

###############################################################################

SKIP: {
  our $application;
  do "t/TestBoilerplate";

  #############################################################################

  Gnome2::URL -> show("http://ftp.freenet.de");
  Gnome2::URL -> show_with_env("http://ftp.freenet.de", [map { "$_=" . $ENV{ $_ } } (keys(%ENV))]);
}
