#!/usr/bin/perl -w
use strict;
use Gnome2;

use constant TESTS => 1;
use Test::More tests => TESTS;

# $Header: /cvsroot/gtk2-perl/gtk2-perl-xs/Gnome2/t/GnomeSound,v 1.1 2004/07/18 17:50:22 kaffeetisch Exp $

###############################################################################

SKIP: {
  our $application;
  do "t/TestBoilerplate";

  #############################################################################

  Gnome2::Sound -> init();
  Gnome2::Sound -> init("localhost");

  warn Gnome2::Sound -> connection_get();
  warn Gnome2::Sound -> sample_load("bla", "bla");
  Gnome2::Sound -> play("bla");

  Gnome2::Sound -> shutdown();
}
