#!/usr/bin/perl -w
use strict;
use Gnome2;

# $Header: /cvsroot/gtk2-perl/gtk2-perl-xs/Gnome2/t/GnomeHelp,v 1.3 2003/12/15 00:17:24 kaffeetisch Exp $

###############################################################################

SKIP: {
  our $application;
  do "t/TestBoilerplate";

  #############################################################################

  Gnome2::Help -> display("zenity.xml");
  Gnome2::Help -> display_desktop($application, "panel", "launchers.html");
  Gnome2::Help -> display_desktop_with_env($application, "panel", "launchers.html", "", [map { "$_=" . $ENV{ $_ } } (keys(%ENV))]);
}
